spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/app-seplag
spring.datasource.username=postgres
spring.datasource.password=123456789

# MinIO
minio.url=http://localhost:9000/
minio.access-key=admin
minio.secret-key=admin123
minio.bucket=albums


