spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/app-seplag
spring.datasource.username=postgres
spring.datasource.password=123456789

# MinIO
minio.url=http://localhost:9001
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=albums


